webhook-service:
  container_name: webhook-sevice
  restart: unless-stopped
  image: smonko/webhook-service
  ports:
    - 9000w:9000
  volumes:
    - '/opt/salt/webhooks/sshkey:/root/.ssh:Z'
    - '/opt/salt/webhooks:/etc/webhook'
